### ISSUE TITLE
about ping speed  

### ISSUE THREAD

**Issue by wk989898** [danielzzz/node-ping#117]
when i ping many ip once,i wait a long time
why i wait for so lang to get result?
how  can i get the result fast?

**Comment by mondwan** [comment]
* you can take a look arguments from your system ping, and our options. You
can take a look the timeout related options since some ping packet lost etc
reasons
* You may post your codes here to demonstrate what u mean on running lost
of ping. In short, you may not utilitizes promises properly

在 2020年4月13日週一 00:05，wangkun <notifications@github.com> 寫道：

**Comment by wk989898** [comment]
i use it in electron 
code 
``` js
  let arr = []
  for (let list of lists) {
    let res = await ping.promise.probe(list.addr, {
      timeout: 10,
    })
    if(res.avg==='unknown') res.avg=0
    arr.push(parseInt(res.avg))
  }
  e.reply('ping-result', arr)
```
some of addr are bad response,i lost time on it.
which option should i set ?

**Comment by mondwan** [comment]
You are not utilize the js promise properly. Please try to combine your code with some promise library like [bluebird][1].

The methodology you should read is `parallel` while you are using `waterfall` in your codes

[1]: http://bluebirdjs.com/docs/coming-from-other-libraries.html

**Comment by wk989898** [comment]
thanks ，it seem fast than before.
by the way ,is it useful if i set timeout option lower?

**Comment by mondwan** [comment]
It depends on your usage.

I suggest you to read discussions in #101 to get better idea on `timeout`, and `deadline` option. It may gives you insights on how to configure them properly regarding to your usage.
