### ISSUE TITLE
Used for third party server satus check

### ISSUE THREAD

**Issue by vibinthamarassery** [danielzzz/node-ping#144]
Can we use for the third party application is up and run ?

**Comment by mondwan** [comment]
Please elaborate your requirements. At the current time being, i guess it
is fine.

 Since you are just pinging the 3rd party server, you can assume it is
alive if it is ping-able

在 2021年8月31日週二 16:28，Vibin Thamarassery ***@***.***> 寫道：

**Comment by vibinthamarassery** [comment]
Thank you for your reply.

My project is to inform me if any of my server, third party application servers , mysql server, mongo server, etc  has been down. 

I wrote a separate node project to inform me the up and down time for the applications. But, it was triggering from each applications. That is a totally wrong approach and I need to work on each application. Now planning to do each applications health check in my own separate project. I need to check even the Firebase FCM is responding or not.

I hope this is enough for the explanation.

**Comment by mondwan** [comment]
Ummm, no comments on your approach.

But, it is worth to note that our library checks whether a host is alive or
not (In layer 3 point of view) but not your applications. In other words,
your service is healthy or not cannot be perfectly reflected by ping status.

For example, ping can be dropped due to firewall or so. But, it does not
mean your application services are out of services. On the other hand, even
the ping is success, it does not mean your services are healthy.

To summaries, if, the assumption, the host is alive, your services are
healthy. Our library shines. Otherwise, you need to find another solutions.
For example, for MySQL, you need to test the connection in your health
check script by using MySQL cli directly

在 2021年8月31日週二 16:53，Vibin Thamarassery ***@***.***> 寫道：

**Comment by vibinthamarassery** [comment]
Thanks for your reply. Much more appreciated.
