### ISSUE TITLE
output does not log special characters 

### ISSUE THREAD

**Issue by DDantasL** [danielzzz/node-ping#155]
hello, I'm using the lib but my language is Portuguese, how do I do to change to utf8?

**Comment by DDantasL** [comment]
the output res 
![image](https://user-images.githubusercontent.com/48628075/203680015-1d82780a-3e3e-4b2f-a222-b613f9d7b09f.png)

**Comment by DDantasL** [comment]
the output 
![Uploading 20221123_222421.png…]()

**Comment by DDantasL** [comment]
![20221123_222421](https://user-images.githubusercontent.com/48628075/203680344-45dcac7f-18d8-49a5-8093-62eef704c1a8.png)

**Comment by mondwan** [comment]
Have you tried to config the system locale through node Js?

**Comment by DDantasL** [comment]
yes, but the output insist to be with that question mask in the special characters

**Comment by mondwan** [comment]
We are using child_process.spawn() in order to run the system ping. I have a quick look on the encoding from the manual. I don't find any useful information.

I will suggest you have a look, and tried to edit following lines of our library in your local installation. We are happy to help & patch the library if you found the way for making it work. Thanks

https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L48

https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L72
