### ISSUE TITLE
Cannot resolve module 'child_process' in ...

### ISSUE THREAD

**Issue by dmason30** [danielzzz/node-ping#58]
When I install this library it does not seem to install the 'child_process' library as a dependency and therefore errors as above.

**Comment by mondwan** [comment]
child process should be builtin for nodejs
Can you provide more information so that we could help?

For example, ping version you are installing, OS version, nodejs version
and errors logs when you are installing

2017年2月2日 22:21，"dmason30" <notifications@github.com>寫道：

**Comment by dmason30** [comment]
Ping version: latest
OS: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-105-generic x86_64)
Node: 7.4.0

The error is that it cannot find 'child_process' module anywhere.

I am using this on a react app built by webpack (ES6). 

webpack: 1.13.2
webpack-dev-serve:  1.16.1
React: 15.3.2

**Comment by mondwan** [comment]
My guess is it will not work as you expect.

Ping is a kind of system command. As you mentioned webpack, react those
frontend libraries, I guess you would like to run ping on the browser.

This will not work as our implementation relies on the native ping in your
OS which does not provided in browser.

If you would like to create a webpage (pages in a router for example) for
using ping command for debugging your network issues, your frontend codes
should send an ajax to backend and let Backend to run ping instead of
calling ping on frontend.


2017年2月2日 23:21，"dmason30" <notifications@github.com>寫道：

**Comment by dmason30** [comment]
Fair enough. The problem is it is the backend that I want to ping and fetch/axios/ajax all fail to handle connection timeouts appropriately.

Please feel free to close.

**Comment by mondwan** [comment]
I guess the timeout you are talking about is the one between your frontend
and backend's connection?

If so, the fetch will throw an error on such timeout. If you are using
promise based fetch, try to catch such error.

2017年2月2日 23:39，"dmason30" <notifications@github.com>寫道：

**Comment by mondwan** [comment]
Close.

**Comment by dmason30** [comment]
Yes that is the issue but the fetch error message is different on every browser and only returns a string. e.g. on chrome  'TypeError: Failed to fetch'.

**Comment by mondwan** [comment]
Have you tried isomorphic fetch?

https://github.com/matthew-andrews/isomorphic-fetch

Last time I had built a project on it. Quite good in my experience although
I am not sure whether it is cross platform or not

2017年2月3日 00:54，"dmason30" <notifications@github.com>寫道：

Yes that is the issue but the fetch error message is different on every
browser and only returns a string. e.g. on chrome 'TypeError: Failed to
fetch'.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/danielzzz/node-ping/issues/58#issuecomment-277014601>,
or mute the thread

**Comment by dmason30** [comment]
That is what I am getting its just a wrapper for fetch/XHR for browser compatibility still returns the same error when request fails (no http status code).
