### ISSUE TITLE
Continuos Ping Output 

### ISSUE THREAD

**Issue by muscaiu** [danielzzz/node-ping#62]
I couldn't find any example for a continuos ping, so i tried to make one myself with Node and Angular.

**Node**
```
'use strict'

var ping = require('ping');
var http = require('http');

module.exports = function (router) {

    var hosts = [
        '8.8.8.8',
        '192.168.1.1',
        '192.168.0.1',
        '192.168.0.2',
        '192.168.0.3',
        '192.168.0.4',
        '192.168.0.5',
        '192.168.0.6',
        '192.168.0.7',
        '192.168.0.8',
    ];
    var messages = [];

    function scan() {
        hosts.forEach(function (host) {
            ping.promise.probe(host, {
                timeout: 2,
                //min_reply: 2,
                // extra: ["-i 2"],
            }).then(function (res) {
                //console.log(`${res.host} ${res.alive} ${res.time}`);
                messages.push({ ip: res.host, status: res.alive, time: res.time })
            });
        });
        console.log('before',messages.length)
        messages = [];
        setTimeout(scan, 5000);
    }

    scan();

    router.post('/getData', function (req, res) {
        console.log('after',messages.length)
        res.send(messages)
    })

    return router //return whatever the route is
}
```
**Angular**
```
    .controller('mainCtrl', function ($http, $timeout) {

        var main = this;

        function scan() {
            $http.post('api/getData', { test: 'testing data' })
                .then(function (response) {
                    console.log(response.data.length)
                    main.pingData = response.data
                })
            setTimeout(scan, 5000);
        }
        scan();

    })
```

This gives like 80% of the time the correct output, and it's not good enough.
![out](https://cloud.githubusercontent.com/assets/11426309/24868127/ce9aaaaa-1e17-11e7-8ce8-7a2369d50e21.jpg)

Any ideas on how could i improve it?

**Comment by mondwan** [comment]
Hello @muscaiu ,

Currently, continuous ping is not supported for this module. Although system ping supports pinging forever with some arguments (For example, window `ping -t 8.8.8.8`), they will not work in our module as implementation of this module is in a batch not in a stream. In other words, it need output of a complete ping progress to work and parse and return information you like.

For your codes, I am not sure the actual purpose. If you need to get a response for a summary overall your pinged hosts, it should be like that

```javascript
    router.post('/getData', function (req, res) {
        q.all(hosts.forEach(function (host) {
            return ping.promise.probe(host, {
                timeout: 2,
                //min_reply: 2,
                // extra: ["-i 2"],
            });
        })
        .then(function (pingResponses) {
            // check out ping responses as I cannot recall what it looks like
            // However, it must contain responses from all your hosts including success or failure
            
            res.send(/*what ever you need from ping response*/)
        })
        .catch(function (err) { console.log(err);});
    })
```

Above codes jump into `then part` immediately if any hosts is unreachable. If that's is not your case, you need following

```javascript
    router.post('/getData', function (req, res) {
        q.allSettled(hosts.forEach(function (host) {
            return ping.promise.probe(host, {
                timeout: 2,
                //min_reply: 2,
                // extra: ["-i 2"],
            });
        })
        .then(function (pingResponses) {
            // check out ping responses as I cannot recall what it looks like
            // However, it must contain responses from all your hosts including success or failure
            
            res.send(/*what ever you need from ping response*/)
        })
        .catch(function (err) { console.log(err);});
    })
```

Maybe, I need more information from you so that I can give more suggestions :P

**Comment by muscaiu** [comment]
Thanks for the link! It's not the 1-st time i hear about this book, but this time i will try to read some of it, even though i find it impossible to keep myself focused reading.

The idea was... since i like JS and Node i figured i make a server that will continuosly ping the local network, serve the data in the browser, save hourly reports to Mongo and create some cool statistics and charts.  It's very important for the reports to be reliable, the pings must give accurate responses.

About the codes, ...what i did is, instead of logging the `res.host`, `res.alive` i would push it to the `messages` array, and then before the function was recalled after 5 seconds, i would empty the array. Then on the front-end, every 5 seconds i would read from that array.
So i think the problem with my weird output is when the 5 seconds from the back-end and the 5 seconds from the front-end colide, the array is being mutilated xD .. and thus the weird output only at some repeated times. I hope you can understand.. xD .. 
And that's why i was asking for other, definetly better ways to do this.

For your examples, first of all i get `q is not defined`, and i guess q is supposed to be a promisse, but i don't know how i could use it. 
Also for the `res.send`, could you give some example, beacuse this `/*what ever you need from ping response*/` doesn't really say much to me.

Sory for too long response! It's actually not much compared to the thing you made me read!! And you asked for it xD

**Comment by mondwan** [comment]
Hello again,

For the `q` one, it is a promise library which you can install via npm

npm install q

For the `res.send`, it is a bit tricky. As what else should be placed here
depends what your frontend need.

For example, if you need to print rtt values for all hosts you have ping,
you need to extract rtt from `responses` and placed there. Then, value will
get passed to your angular calls.

For hour report solution, you need to reconsider what is your data source
and how to put data in your data source and how to retrieve your data
source.

By data source I mean how will you get data from your Backend to frontend.
For example, currently, data source is a kind of on demand. Angular fires a
request. Then, your Backend Ping a list of hosts once and response. That's
the end of story.

This kind of on demand data sources​ does not fit your solution. You need
something runs in the background in your Backend which pings periodically
and dump things into your mongodb. Then, provide APIs for angular to access
your database for history record.





2017年4月11日 17:25，"Cristian Muscalu" <notifications@github.com>寫道：

Thanks for the link! It's not the 1-st time i hear about this book, but
this time i will try to read some of it, even though i find it impossible
to keep myself focused reading.

The idea was... since i like JS and Node i figured i make a server that
will continuosly ping the local network, serve the data in the browser,
save hourly reports to Mongo and create some cool statistics and charts.
It's very important for the reports to be reliable, the pings must give
accurate responses.

About the codes, ...what i did is, instead of logging the res.host,
res.alive i would push it to the messages array, and then before the
function was recalled after 5 seconds, i would empty the array. Then on the
front-end, every 5 seconds i would read from that array.
So i think the problem with my weird output is when the 5 seconds from the
back-end and the 5 seconds from the front-end colide, the array is being
mutilated xD .. and thus the weird output only at some repeated times. I
hope you can understand.. xD ..
And that's why i was asking for other, definetly better ways to do this.

For your examples, first of all i get q is not defined, and i guess q is
supposed to be a promisse, but i don't know how i could use it.
Also for the res.send, could you give some example, beacuse this /*what
ever you need from ping response*/ doesn't really say much to me.

Sory for too long response! It's actually not much compared to the thing
you made me read!! And you asked for it xD

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/danielzzz/node-ping/issues/62#issuecomment-293201722>,
or mute the thread

**Comment by muscaiu** [comment]
I'm not worried about the hour report or the angular data. That will work if the core works.

All i want to do now, is a core Scan() function that will run on the server every 5 seconds, and a Report() function that will just print the current Scan() data. I put 5 seconds, beacuse i want to give it time to breathe and easy to test, but actually i want something close to a live status of the hosts. I want a Live View and a History View, but the Live View that can't be done with Mongo cause it's too much data to be stored. 

I tried doing the Scan and Report on the back-end, but i have the same issue. When the timers tick at the same time, the Report is 0 just like in the example below.

Do you have an idea how could i avoid this timer clash mess? Because no matter what timeouts i would put, there will always be a time when the timers tick at the same time and that data Report will be inacurate.

```
    var hosts = [
        '8.8.8.8',
        '192.168.1.1',
        '192.168.0.8',
    ];
    var messages = [];

    function Scan() {
        hosts.forEach(function (host) {
            ping.promise.probe(host, {
                timeout: 1
            }).then(function (res) {
                messages.push({ ip: res.host, status: res.alive, time: res.time })
            });
        });
        messages.forEach(function (ip) {
            console.log('before', ip.ip, ip.status)
        })
        console.log('------------')
        messages = [];
        setTimeout(Scan, 5000);
    }
    Scan();

    function Report() {
        messages.forEach(function (ip) {
            console.log('after', ip.ip, ip.status)
        })
        console.log('++++++++++++++')
        setTimeout(Report, 5000);
    }
    Report();
```

**Comment by mondwan** [comment]
Let me know if my understanding is correct or not. There are 2 parts for your design.
* There is an infinite loop (`scan()`) with interval 5 seconds for pinging your hosts some how
   * Within each loop you keep 5 responses from pings in `message`
* Angular periodical requests such message with interval 5 seconds by calling `/api/report` for example
   * For each request to `/api/report`, handler for them will take out 5 `message` produced from `scan()`

Actually, this is doable for synchronizing requests between them. Using promises wisely should do the job. However, this does not mean easy as `scan()` and `report()` are interleaving in indeterministic orders as `report()` is triggered by your client side.

Why on demand based approach does not work for you? IE, ping only if there are requests on `report()`. It will be much much easier.

**Comment by mondwan** [comment]
Feel free to reopen it.
