### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by woicha** [danielzzz/node-ping#77]
Hi guys,
I'd like to contribute with an issue and a feature. It seems I haven't got push accesss to this repository. Can someone help me?
Thanks, woicha

**Comment by danielzzz** [comment]
hello, the ideal way of contributing is forking the repository then issuing a pull request.
thank you!
dan

**Comment by woicha** [comment]
Thank you for your prompt answer, I think that's what I did. (Sorry, I'm new to web development an sharing on GiHub)
I'm working with GitHub Desktop on a Windows 10 machine (German); when I try to create a pull request I receive a dialog window which tells me 
"Your branch must be published before opening a pull request"
and offers me the options to "Publish branch" or "Cancel" via a Windows push button. When I try to publish my branch I receive an Error message which tells me that:
"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

Many thanks, Tom.

**Comment by danielzzz** [comment]
sorry, I am not sure what might be the problem... maybe @mondwan will be able to give a hand?

**Comment by mondwan** [comment]
Sure.

After forking a new repository by clicking the button in our GitHub repo,
you should have a new repo under your name.

Then, you can git clone the repo under your name to your workstation

After having your patch ready, you can push them as a new branch under your
repo. Note that some repository you are going to contribute may have rules
for developers to follow. Make sure you have checked out them.

Finally, you can browse the new branch from the GitHub UI. There should be
a button for you to create a pull request.

Here is a reference for you which about how github fork and pull request
works.

https://gist.github.com/6220119/a28375a7940a56b4a1161c8e5fa5b331

Happy coding :)


2018年2月9日 18:32 於 "danielz" <notifications@github.com> 寫道：

sorry, I am not sure what might be the problem... maybe @mondwan
<https://github.com/mondwan> will be able to give a hand?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/danielzzz/node-ping/issues/77#issuecomment-364397007>,
or mute the thread

**Comment by woicha** [comment]
Thank you very much,
I think it worked, I created a new pull request. 
I think the problem was, that I had cloned the repo to my workstation without forking it before. To solve the problem I added a new fork to my cloned repo and after that pushed my branch to that new repo.

Thank's again, Tom.

**Comment by mondwan** [comment]
Great. We will review your patch later on. :)

Close #77

2018年2月9日 19:51 於 "Thomas Walcher" <notifications@github.com> 寫道：
