### ISSUE TITLE
min reply doesn't work on linux (ubuntu) and mac

### ISSUE THREAD

**Issue by adamhancock** [danielzzz/node-ping#90]
I'm using the github code rather NPM but min reply on Linux and Mac doesn't work. It only ever sends two replies. It does however work on Windows. 

```javascript 
ping.promise.probe("8.8.8.8", {
                    min_reply: 10
                }).then((res) => console.log(res))
```
```javascript 
{ host: '8.8.8.8',
  alive: true,
  output:
   'PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.\n64 bytes from 8.8.8.8: icmp_seq=1 ttl=122 time=4.07 ms\n64 bytes from 8.8.8.8: icmp_seq=2 ttl=122 time=3.91 ms\n\n--- 8.8.8.8 ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 3.916/3.994/4.073/0.100 ms\n',
  time: 4.07,
  times: [ 4.07, 3.91 ],
  min: '3.916',
  max: '4.073',
  avg: '3.994',
  stddev: '0.100',
  numeric_host: '8.8.8.8' }
```

**Comment by ThatOneNeji** [comment]
I had the same issue. Try as I might I couldn't get the count to be higher than 3.
It comes down to the "-w" option of the ping utility.
From "man ping"
**-w deadline**
_Specify a timeout, in seconds, before ping exits regardless of how many packets have been sent or received. In this case ping does not stop after count packet are sent, it waits either for deadline expire  or  until count probes are answered or for some error notification from network._

And because you did not specify "timeout: 10", it used the default configuration.

In "lib\builder\linux.js" the following default config is defined:
var defaultConfig = {
    numeric: true,
    **timeout: 2**,
    min_reply: 1,
    extra: []
};

Try the following and see if that resolves your issue:
```
ping.promise.probe("8.8.8.8", {
                    min_reply: 10,
                    timeout: 10
                }).then((res) => console.log(res))
```

**Comment by adamhancock** [comment]
> I had the same issue. Try as I might I couldn't get the count to be higher than 3.
> It comes down to the "-w" option of the ping utility.
> From "man ping"
> **-w deadline**
> _Specify a timeout, in seconds, before ping exits regardless of how many packets have been sent or received. In this case ping does not stop after count packet are sent, it waits either for deadline expire or until count probes are answered or for some error notification from network._
> 
> And because you did not specify "timeout: 10", it used the default configuration.
> 
> In "lib\builder\linux.js" the following default config is defined:
> var defaultConfig = {
> numeric: true,
> **timeout: 2**,
> min_reply: 1,
> extra: []
> };
> 
> Try the following and see if that resolves your issue:
> 
> ```
> ping.promise.probe("8.8.8.8", {
>                     min_reply: 10,
>                     timeout: 10
>                 }).then((res) => console.log(res))
> ```

That worked! thank you very much for replying.

**Comment by mondwan** [comment]
Close as problem solved
