### ISSUE TITLE
Include user-passed host in body.

### ISSUE THREAD

**Issue by bnb** [danielzzz/node-ping#98]
I'm currently working on dynamically pinging ~140 servers. The URLs I'm pinging are _apparently_ aliases for the actual underlying servers. The underlying server URLs are not static but rather dynamic.

It would be awesome to be able to map 1:1 the URL that was input as a host to the URL that was output as a host.

Thank you for this module 💖

**Comment by mondwan** [comment]
Tell me if I am not understand your question. You would like to ping a list of Servers. Those server s are not static IP. And, you expect to ping those servers in one call. If that's the case, try to make use of Promise library for compositing ping promises for each of your server. For dynamic IP, just type in the hostname instead of IP. We r using system ping. It should be able to resolve the hostname dynamically
